python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/10420/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/10420
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/10973/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/10973
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/1117/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/1117
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/1156/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/1156
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/12016/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/12016
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/12601/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/12601
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/12665/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/12665
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/12691/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/12691
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/12802/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/12802
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/1283/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/1283
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/13662/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/13662
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/13685/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/13685
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/13849/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/13849
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/14011/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/14011
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/14209/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/14209
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/14525/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/14525
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/14864/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/14864
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/14969/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/14969
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/15083/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/15083
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/15207/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/15207
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/1561/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/1561
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/17515/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/17515
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/17801/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/17801
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/18043/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/18043
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/18118/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/18118
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/18816/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/18816
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/1937/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/1937
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/19510/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/19510
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/20003/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/20003
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/2586/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/2586
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/2679/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/2679
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/3759/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/3759
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/388/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/388
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/3985/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/3985
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/433/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/433
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/4589/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/4589
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/4945/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/4945
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/516/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/516
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/5338/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/5338
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/6113/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/6113
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/6271/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/6271
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/6497/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/6497
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/7066/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/7066
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/7217/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/7217
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/7218/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/7218
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/7288/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/7288
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/7633/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/7633
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/7837/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/7837
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/8056/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/8056
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/8166/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/8166
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/8192/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/8192
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/8303/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/8303
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/9061/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/9061
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/9224/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/9224
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/934/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/934
python tcr_builder.py /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/9484/template.csv /home/andrefonseca/Projects/cross_structure/data/vdj_xreaction/9484
